//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"
namespace FIRRTLFrontend
{
/********************   ECircuit    ********************/
ECircuit::ECircuit(Id *p1, Info *p2, ListModule *p3)
{
  id_ = p1;
  info_ = p2;
  listmodule_ = p3;

}

ECircuit::ECircuit(const ECircuit & other)
{
  id_ = other.id_->clone();
  info_ = other.info_->clone();
  listmodule_ = other.listmodule_->clone();

}

ECircuit &ECircuit::operator=(const ECircuit & other)
{
  ECircuit tmp(other);
  swap(tmp);
  return *this;
}

void ECircuit::swap(ECircuit & other)
{
  std::swap(id_, other.id_);
  std::swap(info_, other.info_);
  std::swap(listmodule_, other.listmodule_);

}

ECircuit::~ECircuit()
{
  delete(id_);
  delete(info_);
  delete(listmodule_);

}

void ECircuit::accept(Visitor *v)
{
  v->visitECircuit(this);
}

ECircuit *ECircuit::clone() const
{
  return new ECircuit(*this);
}



/********************   Module1    ********************/
Module1::Module1(Id *p1, Info *p2, ListPort *p3, Stmt *p4)
{
  id_ = p1;
  info_ = p2;
  listport_ = p3;
  stmt_ = p4;

}

Module1::Module1(const Module1 & other)
{
  id_ = other.id_->clone();
  info_ = other.info_->clone();
  listport_ = other.listport_->clone();
  stmt_ = other.stmt_->clone();

}

Module1 &Module1::operator=(const Module1 & other)
{
  Module1 tmp(other);
  swap(tmp);
  return *this;
}

void Module1::swap(Module1 & other)
{
  std::swap(id_, other.id_);
  std::swap(info_, other.info_);
  std::swap(listport_, other.listport_);
  std::swap(stmt_, other.stmt_);

}

Module1::~Module1()
{
  delete(id_);
  delete(info_);
  delete(listport_);
  delete(stmt_);

}

void Module1::accept(Visitor *v)
{
  v->visitModule1(this);
}

Module1 *Module1::clone() const
{
  return new Module1(*this);
}



/********************   Module2    ********************/
Module2::Module2(Id *p1, Info *p2, ListPort *p3)
{
  id_ = p1;
  info_ = p2;
  listport_ = p3;

}

Module2::Module2(const Module2 & other)
{
  id_ = other.id_->clone();
  info_ = other.info_->clone();
  listport_ = other.listport_->clone();

}

Module2 &Module2::operator=(const Module2 & other)
{
  Module2 tmp(other);
  swap(tmp);
  return *this;
}

void Module2::swap(Module2 & other)
{
  std::swap(id_, other.id_);
  std::swap(info_, other.info_);
  std::swap(listport_, other.listport_);

}

Module2::~Module2()
{
  delete(id_);
  delete(info_);
  delete(listport_);

}

void Module2::accept(Visitor *v)
{
  v->visitModule2(this);
}

Module2 *Module2::clone() const
{
  return new Module2(*this);
}



/********************   EPort    ********************/
EPort::EPort(Dir *p1, Id *p2, Type *p3, Info *p4)
{
  dir_ = p1;
  id_ = p2;
  type_ = p3;
  info_ = p4;

}

EPort::EPort(const EPort & other)
{
  dir_ = other.dir_->clone();
  id_ = other.id_->clone();
  type_ = other.type_->clone();
  info_ = other.info_->clone();

}

EPort &EPort::operator=(const EPort & other)
{
  EPort tmp(other);
  swap(tmp);
  return *this;
}

void EPort::swap(EPort & other)
{
  std::swap(dir_, other.dir_);
  std::swap(id_, other.id_);
  std::swap(type_, other.type_);
  std::swap(info_, other.info_);

}

EPort::~EPort()
{
  delete(dir_);
  delete(id_);
  delete(type_);
  delete(info_);

}

void EPort::accept(Visitor *v)
{
  v->visitEPort(this);
}

EPort *EPort::clone() const
{
  return new EPort(*this);
}



/********************   Dir_input    ********************/
Dir_input::Dir_input()
{

}

Dir_input::Dir_input(const Dir_input & other)
{

}

Dir_input &Dir_input::operator=(const Dir_input & other)
{
  Dir_input tmp(other);
  swap(tmp);
  return *this;
}

void Dir_input::swap(Dir_input & other)
{

}

Dir_input::~Dir_input()
{

}

void Dir_input::accept(Visitor *v)
{
  v->visitDir_input(this);
}

Dir_input *Dir_input::clone() const
{
  return new Dir_input(*this);
}



/********************   Dir_output    ********************/
Dir_output::Dir_output()
{

}

Dir_output::Dir_output(const Dir_output & other)
{

}

Dir_output &Dir_output::operator=(const Dir_output & other)
{
  Dir_output tmp(other);
  swap(tmp);
  return *this;
}

void Dir_output::swap(Dir_output & other)
{

}

Dir_output::~Dir_output()
{

}

void Dir_output::accept(Visitor *v)
{
  v->visitDir_output(this);
}

Dir_output *Dir_output::clone() const
{
  return new Dir_output(*this);
}



/********************   Type1    ********************/
Type1::Type1(Intsize *p1)
{
  intsize_ = p1;

}

Type1::Type1(const Type1 & other)
{
  intsize_ = other.intsize_->clone();

}

Type1 &Type1::operator=(const Type1 & other)
{
  Type1 tmp(other);
  swap(tmp);
  return *this;
}

void Type1::swap(Type1 & other)
{
  std::swap(intsize_, other.intsize_);

}

Type1::~Type1()
{
  delete(intsize_);

}

void Type1::accept(Visitor *v)
{
  v->visitType1(this);
}

Type1 *Type1::clone() const
{
  return new Type1(*this);
}



/********************   Type2    ********************/
Type2::Type2(Intsize *p1)
{
  intsize_ = p1;

}

Type2::Type2(const Type2 & other)
{
  intsize_ = other.intsize_->clone();

}

Type2 &Type2::operator=(const Type2 & other)
{
  Type2 tmp(other);
  swap(tmp);
  return *this;
}

void Type2::swap(Type2 & other)
{
  std::swap(intsize_, other.intsize_);

}

Type2::~Type2()
{
  delete(intsize_);

}

void Type2::accept(Visitor *v)
{
  v->visitType2(this);
}

Type2 *Type2::clone() const
{
  return new Type2(*this);
}



/********************   Type3    ********************/
Type3::Type3(Intsize *p1, Intsizefixed *p2)
{
  intsize_ = p1;
  intsizefixed_ = p2;

}

Type3::Type3(const Type3 & other)
{
  intsize_ = other.intsize_->clone();
  intsizefixed_ = other.intsizefixed_->clone();

}

Type3 &Type3::operator=(const Type3 & other)
{
  Type3 tmp(other);
  swap(tmp);
  return *this;
}

void Type3::swap(Type3 & other)
{
  std::swap(intsize_, other.intsize_);
  std::swap(intsizefixed_, other.intsizefixed_);

}

Type3::~Type3()
{
  delete(intsize_);
  delete(intsizefixed_);

}

void Type3::accept(Visitor *v)
{
  v->visitType3(this);
}

Type3 *Type3::clone() const
{
  return new Type3(*this);
}



/********************   Type_Clock    ********************/
Type_Clock::Type_Clock()
{

}

Type_Clock::Type_Clock(const Type_Clock & other)
{

}

Type_Clock &Type_Clock::operator=(const Type_Clock & other)
{
  Type_Clock tmp(other);
  swap(tmp);
  return *this;
}

void Type_Clock::swap(Type_Clock & other)
{

}

Type_Clock::~Type_Clock()
{

}

void Type_Clock::accept(Visitor *v)
{
  v->visitType_Clock(this);
}

Type_Clock *Type_Clock::clone() const
{
  return new Type_Clock(*this);
}



/********************   Type4    ********************/
Type4::Type4(Intsize *p1)
{
  intsize_ = p1;

}

Type4::Type4(const Type4 & other)
{
  intsize_ = other.intsize_->clone();

}

Type4 &Type4::operator=(const Type4 & other)
{
  Type4 tmp(other);
  swap(tmp);
  return *this;
}

void Type4::swap(Type4 & other)
{
  std::swap(intsize_, other.intsize_);

}

Type4::~Type4()
{
  delete(intsize_);

}

void Type4::accept(Visitor *v)
{
  v->visitType4(this);
}

Type4 *Type4::clone() const
{
  return new Type4(*this);
}



/********************   Type5    ********************/
Type5::Type5(ListField *p1)
{
  listfield_ = p1;

}

Type5::Type5(const Type5 & other)
{
  listfield_ = other.listfield_->clone();

}

Type5 &Type5::operator=(const Type5 & other)
{
  Type5 tmp(other);
  swap(tmp);
  return *this;
}

void Type5::swap(Type5 & other)
{
  std::swap(listfield_, other.listfield_);

}

Type5::~Type5()
{
  delete(listfield_);

}

void Type5::accept(Visitor *v)
{
  v->visitType5(this);
}

Type5 *Type5::clone() const
{
  return new Type5(*this);
}



/********************   Type6    ********************/
Type6::Type6(Type *p1, Int *p2)
{
  type_ = p1;
  int_ = p2;

}

Type6::Type6(const Type6 & other)
{
  type_ = other.type_->clone();
  int_ = other.int_->clone();

}

Type6 &Type6::operator=(const Type6 & other)
{
  Type6 tmp(other);
  swap(tmp);
  return *this;
}

void Type6::swap(Type6 & other)
{
  std::swap(type_, other.type_);
  std::swap(int_, other.int_);

}

Type6::~Type6()
{
  delete(type_);
  delete(int_);

}

void Type6::accept(Visitor *v)
{
  v->visitType6(this);
}

Type6 *Type6::clone() const
{
  return new Type6(*this);
}



/********************   EField    ********************/
EField::EField(Flipliteral *p1, Id *p2, Type *p3)
{
  flipliteral_ = p1;
  id_ = p2;
  type_ = p3;

}

EField::EField(const EField & other)
{
  flipliteral_ = other.flipliteral_->clone();
  id_ = other.id_->clone();
  type_ = other.type_->clone();

}

EField &EField::operator=(const EField & other)
{
  EField tmp(other);
  swap(tmp);
  return *this;
}

void EField::swap(EField & other)
{
  std::swap(flipliteral_, other.flipliteral_);
  std::swap(id_, other.id_);
  std::swap(type_, other.type_);

}

EField::~EField()
{
  delete(flipliteral_);
  delete(id_);
  delete(type_);

}

void EField::accept(Visitor *v)
{
  v->visitEField(this);
}

EField *EField::clone() const
{
  return new EField(*this);
}



/********************   Flipliteral_flip    ********************/
Flipliteral_flip::Flipliteral_flip()
{

}

Flipliteral_flip::Flipliteral_flip(const Flipliteral_flip & other)
{

}

Flipliteral_flip &Flipliteral_flip::operator=(const Flipliteral_flip & other)
{
  Flipliteral_flip tmp(other);
  swap(tmp);
  return *this;
}

void Flipliteral_flip::swap(Flipliteral_flip & other)
{

}

Flipliteral_flip::~Flipliteral_flip()
{

}

void Flipliteral_flip::accept(Visitor *v)
{
  v->visitFlipliteral_flip(this);
}

Flipliteral_flip *Flipliteral_flip::clone() const
{
  return new Flipliteral_flip(*this);
}



/********************   Flipliteral_    ********************/
Flipliteral_::Flipliteral_()
{

}

Flipliteral_::Flipliteral_(const Flipliteral_ & other)
{

}

Flipliteral_ &Flipliteral_::operator=(const Flipliteral_ & other)
{
  Flipliteral_ tmp(other);
  swap(tmp);
  return *this;
}

void Flipliteral_::swap(Flipliteral_ & other)
{

}

Flipliteral_::~Flipliteral_()
{

}

void Flipliteral_::accept(Visitor *v)
{
  v->visitFlipliteral_(this);
}

Flipliteral_ *Flipliteral_::clone() const
{
  return new Flipliteral_(*this);
}



/********************   Stmt1    ********************/
Stmt1::Stmt1(Id *p1, Type *p2, Info *p3)
{
  id_ = p1;
  type_ = p2;
  info_ = p3;

}

Stmt1::Stmt1(const Stmt1 & other)
{
  id_ = other.id_->clone();
  type_ = other.type_->clone();
  info_ = other.info_->clone();

}

Stmt1 &Stmt1::operator=(const Stmt1 & other)
{
  Stmt1 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt1::swap(Stmt1 & other)
{
  std::swap(id_, other.id_);
  std::swap(type_, other.type_);
  std::swap(info_, other.info_);

}

Stmt1::~Stmt1()
{
  delete(id_);
  delete(type_);
  delete(info_);

}

void Stmt1::accept(Visitor *v)
{
  v->visitStmt1(this);
}

Stmt1 *Stmt1::clone() const
{
  return new Stmt1(*this);
}



/********************   Stmt2    ********************/
Stmt2::Stmt2(Id *p1, Type *p2, Exp *p3, Withreset *p4, Info *p5)
{
  id_ = p1;
  type_ = p2;
  exp_ = p3;
  withreset_ = p4;
  info_ = p5;

}

Stmt2::Stmt2(const Stmt2 & other)
{
  id_ = other.id_->clone();
  type_ = other.type_->clone();
  exp_ = other.exp_->clone();
  withreset_ = other.withreset_->clone();
  info_ = other.info_->clone();

}

Stmt2 &Stmt2::operator=(const Stmt2 & other)
{
  Stmt2 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt2::swap(Stmt2 & other)
{
  std::swap(id_, other.id_);
  std::swap(type_, other.type_);
  std::swap(exp_, other.exp_);
  std::swap(withreset_, other.withreset_);
  std::swap(info_, other.info_);

}

Stmt2::~Stmt2()
{
  delete(id_);
  delete(type_);
  delete(exp_);
  delete(withreset_);
  delete(info_);

}

void Stmt2::accept(Visitor *v)
{
  v->visitStmt2(this);
}

Stmt2 *Stmt2::clone() const
{
  return new Stmt2(*this);
}



/********************   Stmt3    ********************/
Stmt3::Stmt3(Id *p1, Info *p2, Type *p3, Int *p4, Int *p5, Int *p6, Ruw *p7, ListReader *p8, ListWriter *p9, ListReadwriter *p10)
{
  id_ = p1;
  info_ = p2;
  type_ = p3;
  int_1 = p4;
  int_2 = p5;
  int_3 = p6;
  ruw_ = p7;
  listreader_ = p8;
  listwriter_ = p9;
  listreadwriter_ = p10;

}

Stmt3::Stmt3(const Stmt3 & other)
{
  id_ = other.id_->clone();
  info_ = other.info_->clone();
  type_ = other.type_->clone();
  int_1 = other.int_1->clone();
  int_2 = other.int_2->clone();
  int_3 = other.int_3->clone();
  ruw_ = other.ruw_->clone();
  listreader_ = other.listreader_->clone();
  listwriter_ = other.listwriter_->clone();
  listreadwriter_ = other.listreadwriter_->clone();

}

Stmt3 &Stmt3::operator=(const Stmt3 & other)
{
  Stmt3 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt3::swap(Stmt3 & other)
{
  std::swap(id_, other.id_);
  std::swap(info_, other.info_);
  std::swap(type_, other.type_);
  std::swap(int_1, other.int_1);
  std::swap(int_2, other.int_2);
  std::swap(int_3, other.int_3);
  std::swap(ruw_, other.ruw_);
  std::swap(listreader_, other.listreader_);
  std::swap(listwriter_, other.listwriter_);
  std::swap(listreadwriter_, other.listreadwriter_);

}

Stmt3::~Stmt3()
{
  delete(id_);
  delete(info_);
  delete(type_);
  delete(int_1);
  delete(int_2);
  delete(int_3);
  delete(ruw_);
  delete(listreader_);
  delete(listwriter_);
  delete(listreadwriter_);

}

void Stmt3::accept(Visitor *v)
{
  v->visitStmt3(this);
}

Stmt3 *Stmt3::clone() const
{
  return new Stmt3(*this);
}



/********************   Stmt4    ********************/
Stmt4::Stmt4(Id *p1, Id *p2, Info *p3)
{
  id_1 = p1;
  id_2 = p2;
  info_ = p3;

}

Stmt4::Stmt4(const Stmt4 & other)
{
  id_1 = other.id_1->clone();
  id_2 = other.id_2->clone();
  info_ = other.info_->clone();

}

Stmt4 &Stmt4::operator=(const Stmt4 & other)
{
  Stmt4 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt4::swap(Stmt4 & other)
{
  std::swap(id_1, other.id_1);
  std::swap(id_2, other.id_2);
  std::swap(info_, other.info_);

}

Stmt4::~Stmt4()
{
  delete(id_1);
  delete(id_2);
  delete(info_);

}

void Stmt4::accept(Visitor *v)
{
  v->visitStmt4(this);
}

Stmt4 *Stmt4::clone() const
{
  return new Stmt4(*this);
}



/********************   Stmt5    ********************/
Stmt5::Stmt5(Id *p1, Exp *p2, Info *p3)
{
  id_ = p1;
  exp_ = p2;
  info_ = p3;

}

Stmt5::Stmt5(const Stmt5 & other)
{
  id_ = other.id_->clone();
  exp_ = other.exp_->clone();
  info_ = other.info_->clone();

}

Stmt5 &Stmt5::operator=(const Stmt5 & other)
{
  Stmt5 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt5::swap(Stmt5 & other)
{
  std::swap(id_, other.id_);
  std::swap(exp_, other.exp_);
  std::swap(info_, other.info_);

}

Stmt5::~Stmt5()
{
  delete(id_);
  delete(exp_);
  delete(info_);

}

void Stmt5::accept(Visitor *v)
{
  v->visitStmt5(this);
}

Stmt5 *Stmt5::clone() const
{
  return new Stmt5(*this);
}



/********************   Stmt6    ********************/
Stmt6::Stmt6(Exp *p1, Exp *p2, Info *p3)
{
  exp_1 = p1;
  exp_2 = p2;
  info_ = p3;

}

Stmt6::Stmt6(const Stmt6 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();
  info_ = other.info_->clone();

}

Stmt6 &Stmt6::operator=(const Stmt6 & other)
{
  Stmt6 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt6::swap(Stmt6 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);
  std::swap(info_, other.info_);

}

Stmt6::~Stmt6()
{
  delete(exp_1);
  delete(exp_2);
  delete(info_);

}

void Stmt6::accept(Visitor *v)
{
  v->visitStmt6(this);
}

Stmt6 *Stmt6::clone() const
{
  return new Stmt6(*this);
}



/********************   Stmt7    ********************/
Stmt7::Stmt7(Exp *p1, Exp *p2, Info *p3)
{
  exp_1 = p1;
  exp_2 = p2;
  info_ = p3;

}

Stmt7::Stmt7(const Stmt7 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();
  info_ = other.info_->clone();

}

Stmt7 &Stmt7::operator=(const Stmt7 & other)
{
  Stmt7 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt7::swap(Stmt7 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);
  std::swap(info_, other.info_);

}

Stmt7::~Stmt7()
{
  delete(exp_1);
  delete(exp_2);
  delete(info_);

}

void Stmt7::accept(Visitor *v)
{
  v->visitStmt7(this);
}

Stmt7 *Stmt7::clone() const
{
  return new Stmt7(*this);
}



/********************   Stmt8    ********************/
Stmt8::Stmt8(Exp *p1, Info *p2)
{
  exp_ = p1;
  info_ = p2;

}

Stmt8::Stmt8(const Stmt8 & other)
{
  exp_ = other.exp_->clone();
  info_ = other.info_->clone();

}

Stmt8 &Stmt8::operator=(const Stmt8 & other)
{
  Stmt8 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt8::swap(Stmt8 & other)
{
  std::swap(exp_, other.exp_);
  std::swap(info_, other.info_);

}

Stmt8::~Stmt8()
{
  delete(exp_);
  delete(info_);

}

void Stmt8::accept(Visitor *v)
{
  v->visitStmt8(this);
}

Stmt8 *Stmt8::clone() const
{
  return new Stmt8(*this);
}



/********************   Stmt9    ********************/
Stmt9::Stmt9(ListExp *p1, Info *p2)
{
  listexp_ = p1;
  info_ = p2;

}

Stmt9::Stmt9(const Stmt9 & other)
{
  listexp_ = other.listexp_->clone();
  info_ = other.info_->clone();

}

Stmt9 &Stmt9::operator=(const Stmt9 & other)
{
  Stmt9 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt9::swap(Stmt9 & other)
{
  std::swap(listexp_, other.listexp_);
  std::swap(info_, other.info_);

}

Stmt9::~Stmt9()
{
  delete(listexp_);
  delete(info_);

}

void Stmt9::accept(Visitor *v)
{
  v->visitStmt9(this);
}

Stmt9 *Stmt9::clone() const
{
  return new Stmt9(*this);
}



/********************   Stmt10    ********************/
Stmt10::Stmt10(Exp *p1, Info *p2, Stmt *p3, Elsestmt *p4)
{
  exp_ = p1;
  info_ = p2;
  stmt_ = p3;
  elsestmt_ = p4;

}

Stmt10::Stmt10(const Stmt10 & other)
{
  exp_ = other.exp_->clone();
  info_ = other.info_->clone();
  stmt_ = other.stmt_->clone();
  elsestmt_ = other.elsestmt_->clone();

}

Stmt10 &Stmt10::operator=(const Stmt10 & other)
{
  Stmt10 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt10::swap(Stmt10 & other)
{
  std::swap(exp_, other.exp_);
  std::swap(info_, other.info_);
  std::swap(stmt_, other.stmt_);
  std::swap(elsestmt_, other.elsestmt_);

}

Stmt10::~Stmt10()
{
  delete(exp_);
  delete(info_);
  delete(stmt_);
  delete(elsestmt_);

}

void Stmt10::accept(Visitor *v)
{
  v->visitStmt10(this);
}

Stmt10 *Stmt10::clone() const
{
  return new Stmt10(*this);
}



/********************   Stmt11    ********************/
Stmt11::Stmt11(Exp *p1, Exp *p2, Int *p3, Colonid *p4, Info *p5)
{
  exp_1 = p1;
  exp_2 = p2;
  int_ = p3;
  colonid_ = p4;
  info_ = p5;

}

Stmt11::Stmt11(const Stmt11 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();
  int_ = other.int_->clone();
  colonid_ = other.colonid_->clone();
  info_ = other.info_->clone();

}

Stmt11 &Stmt11::operator=(const Stmt11 & other)
{
  Stmt11 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt11::swap(Stmt11 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);
  std::swap(int_, other.int_);
  std::swap(colonid_, other.colonid_);
  std::swap(info_, other.info_);

}

Stmt11::~Stmt11()
{
  delete(exp_1);
  delete(exp_2);
  delete(int_);
  delete(colonid_);
  delete(info_);

}

void Stmt11::accept(Visitor *v)
{
  v->visitStmt11(this);
}

Stmt11 *Stmt11::clone() const
{
  return new Stmt11(*this);
}



/********************   Stmt12    ********************/
Stmt12::Stmt12(Exp *p1, Exp *p2, SString *p3, ListExp *p4, Colonid *p5, Info *p6)
{
  exp_1 = p1;
  exp_2 = p2;
  sstring_ = p3;
  listexp_ = p4;
  colonid_ = p5;
  info_ = p6;

}

Stmt12::Stmt12(const Stmt12 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();
  sstring_ = other.sstring_->clone();
  listexp_ = other.listexp_->clone();
  colonid_ = other.colonid_->clone();
  info_ = other.info_->clone();

}

Stmt12 &Stmt12::operator=(const Stmt12 & other)
{
  Stmt12 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt12::swap(Stmt12 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);
  std::swap(sstring_, other.sstring_);
  std::swap(listexp_, other.listexp_);
  std::swap(colonid_, other.colonid_);
  std::swap(info_, other.info_);

}

Stmt12::~Stmt12()
{
  delete(exp_1);
  delete(exp_2);
  delete(sstring_);
  delete(listexp_);
  delete(colonid_);
  delete(info_);

}

void Stmt12::accept(Visitor *v)
{
  v->visitStmt12(this);
}

Stmt12 *Stmt12::clone() const
{
  return new Stmt12(*this);
}



/********************   Stmt13    ********************/
Stmt13::Stmt13(Info *p1)
{
  info_ = p1;

}

Stmt13::Stmt13(const Stmt13 & other)
{
  info_ = other.info_->clone();

}

Stmt13 &Stmt13::operator=(const Stmt13 & other)
{
  Stmt13 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt13::swap(Stmt13 & other)
{
  std::swap(info_, other.info_);

}

Stmt13::~Stmt13()
{
  delete(info_);

}

void Stmt13::accept(Visitor *v)
{
  v->visitStmt13(this);
}

Stmt13 *Stmt13::clone() const
{
  return new Stmt13(*this);
}



/********************   Stmt14    ********************/
Stmt14::Stmt14(ListStmt *p1)
{
  liststmt_ = p1;

}

Stmt14::Stmt14(const Stmt14 & other)
{
  liststmt_ = other.liststmt_->clone();

}

Stmt14 &Stmt14::operator=(const Stmt14 & other)
{
  Stmt14 tmp(other);
  swap(tmp);
  return *this;
}

void Stmt14::swap(Stmt14 & other)
{
  std::swap(liststmt_, other.liststmt_);

}

Stmt14::~Stmt14()
{
  delete(liststmt_);

}

void Stmt14::accept(Visitor *v)
{
  v->visitStmt14(this);
}

Stmt14 *Stmt14::clone() const
{
  return new Stmt14(*this);
}



/********************   EReader    ********************/
EReader::EReader(Id *p1)
{
  id_ = p1;

}

EReader::EReader(const EReader & other)
{
  id_ = other.id_->clone();

}

EReader &EReader::operator=(const EReader & other)
{
  EReader tmp(other);
  swap(tmp);
  return *this;
}

void EReader::swap(EReader & other)
{
  std::swap(id_, other.id_);

}

EReader::~EReader()
{
  delete(id_);

}

void EReader::accept(Visitor *v)
{
  v->visitEReader(this);
}

EReader *EReader::clone() const
{
  return new EReader(*this);
}



/********************   EWriter    ********************/
EWriter::EWriter(Id *p1)
{
  id_ = p1;

}

EWriter::EWriter(const EWriter & other)
{
  id_ = other.id_->clone();

}

EWriter &EWriter::operator=(const EWriter & other)
{
  EWriter tmp(other);
  swap(tmp);
  return *this;
}

void EWriter::swap(EWriter & other)
{
  std::swap(id_, other.id_);

}

EWriter::~EWriter()
{
  delete(id_);

}

void EWriter::accept(Visitor *v)
{
  v->visitEWriter(this);
}

EWriter *EWriter::clone() const
{
  return new EWriter(*this);
}



/********************   EReadWriter    ********************/
EReadWriter::EReadWriter(Id *p1)
{
  id_ = p1;

}

EReadWriter::EReadWriter(const EReadWriter & other)
{
  id_ = other.id_->clone();

}

EReadWriter &EReadWriter::operator=(const EReadWriter & other)
{
  EReadWriter tmp(other);
  swap(tmp);
  return *this;
}

void EReadWriter::swap(EReadWriter & other)
{
  std::swap(id_, other.id_);

}

EReadWriter::~EReadWriter()
{
  delete(id_);

}

void EReadWriter::accept(Visitor *v)
{
  v->visitEReadWriter(this);
}

EReadWriter *EReadWriter::clone() const
{
  return new EReadWriter(*this);
}



/********************   Colonid1    ********************/
Colonid1::Colonid1(Id *p1)
{
  id_ = p1;

}

Colonid1::Colonid1(const Colonid1 & other)
{
  id_ = other.id_->clone();

}

Colonid1 &Colonid1::operator=(const Colonid1 & other)
{
  Colonid1 tmp(other);
  swap(tmp);
  return *this;
}

void Colonid1::swap(Colonid1 & other)
{
  std::swap(id_, other.id_);

}

Colonid1::~Colonid1()
{
  delete(id_);

}

void Colonid1::accept(Visitor *v)
{
  v->visitColonid1(this);
}

Colonid1 *Colonid1::clone() const
{
  return new Colonid1(*this);
}



/********************   Colonid_    ********************/
Colonid_::Colonid_()
{

}

Colonid_::Colonid_(const Colonid_ & other)
{

}

Colonid_ &Colonid_::operator=(const Colonid_ & other)
{
  Colonid_ tmp(other);
  swap(tmp);
  return *this;
}

void Colonid_::swap(Colonid_ & other)
{

}

Colonid_::~Colonid_()
{

}

void Colonid_::accept(Visitor *v)
{
  v->visitColonid_(this);
}

Colonid_ *Colonid_::clone() const
{
  return new Colonid_(*this);
}



/********************   Elsestmt1    ********************/
Elsestmt1::Elsestmt1(Stmt *p1)
{
  stmt_ = p1;

}

Elsestmt1::Elsestmt1(const Elsestmt1 & other)
{
  stmt_ = other.stmt_->clone();

}

Elsestmt1 &Elsestmt1::operator=(const Elsestmt1 & other)
{
  Elsestmt1 tmp(other);
  swap(tmp);
  return *this;
}

void Elsestmt1::swap(Elsestmt1 & other)
{
  std::swap(stmt_, other.stmt_);

}

Elsestmt1::~Elsestmt1()
{
  delete(stmt_);

}

void Elsestmt1::accept(Visitor *v)
{
  v->visitElsestmt1(this);
}

Elsestmt1 *Elsestmt1::clone() const
{
  return new Elsestmt1(*this);
}



/********************   Elsestmt_    ********************/
Elsestmt_::Elsestmt_()
{

}

Elsestmt_::Elsestmt_(const Elsestmt_ & other)
{

}

Elsestmt_ &Elsestmt_::operator=(const Elsestmt_ & other)
{
  Elsestmt_ tmp(other);
  swap(tmp);
  return *this;
}

void Elsestmt_::swap(Elsestmt_ & other)
{

}

Elsestmt_::~Elsestmt_()
{

}

void Elsestmt_::accept(Visitor *v)
{
  v->visitElsestmt_(this);
}

Elsestmt_ *Elsestmt_::clone() const
{
  return new Elsestmt_(*this);
}



/********************   Withreset1    ********************/
Withreset1::Withreset1(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

Withreset1::Withreset1(const Withreset1 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

Withreset1 &Withreset1::operator=(const Withreset1 & other)
{
  Withreset1 tmp(other);
  swap(tmp);
  return *this;
}

void Withreset1::swap(Withreset1 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

Withreset1::~Withreset1()
{
  delete(exp_1);
  delete(exp_2);

}

void Withreset1::accept(Visitor *v)
{
  v->visitWithreset1(this);
}

Withreset1 *Withreset1::clone() const
{
  return new Withreset1(*this);
}



/********************   Withreset_    ********************/
Withreset_::Withreset_()
{

}

Withreset_::Withreset_(const Withreset_ & other)
{

}

Withreset_ &Withreset_::operator=(const Withreset_ & other)
{
  Withreset_ tmp(other);
  swap(tmp);
  return *this;
}

void Withreset_::swap(Withreset_ & other)
{

}

Withreset_::~Withreset_()
{

}

void Withreset_::accept(Visitor *v)
{
  v->visitWithreset_(this);
}

Withreset_ *Withreset_::clone() const
{
  return new Withreset_(*this);
}



/********************   Ruw_old    ********************/
Ruw_old::Ruw_old()
{

}

Ruw_old::Ruw_old(const Ruw_old & other)
{

}

Ruw_old &Ruw_old::operator=(const Ruw_old & other)
{
  Ruw_old tmp(other);
  swap(tmp);
  return *this;
}

void Ruw_old::swap(Ruw_old & other)
{

}

Ruw_old::~Ruw_old()
{

}

void Ruw_old::accept(Visitor *v)
{
  v->visitRuw_old(this);
}

Ruw_old *Ruw_old::clone() const
{
  return new Ruw_old(*this);
}



/********************   Ruw_new    ********************/
Ruw_new::Ruw_new()
{

}

Ruw_new::Ruw_new(const Ruw_new & other)
{

}

Ruw_new &Ruw_new::operator=(const Ruw_new & other)
{
  Ruw_new tmp(other);
  swap(tmp);
  return *this;
}

void Ruw_new::swap(Ruw_new & other)
{

}

Ruw_new::~Ruw_new()
{

}

void Ruw_new::accept(Visitor *v)
{
  v->visitRuw_new(this);
}

Ruw_new *Ruw_new::clone() const
{
  return new Ruw_new(*this);
}



/********************   Ruw_undefined    ********************/
Ruw_undefined::Ruw_undefined()
{

}

Ruw_undefined::Ruw_undefined(const Ruw_undefined & other)
{

}

Ruw_undefined &Ruw_undefined::operator=(const Ruw_undefined & other)
{
  Ruw_undefined tmp(other);
  swap(tmp);
  return *this;
}

void Ruw_undefined::swap(Ruw_undefined & other)
{

}

Ruw_undefined::~Ruw_undefined()
{

}

void Ruw_undefined::accept(Visitor *v)
{
  v->visitRuw_undefined(this);
}

Ruw_undefined *Ruw_undefined::clone() const
{
  return new Ruw_undefined(*this);
}



/********************   Info1    ********************/
Info1::Info1(SString *p1)
{
  sstring_ = p1;

}

Info1::Info1(const Info1 & other)
{
  sstring_ = other.sstring_->clone();

}

Info1 &Info1::operator=(const Info1 & other)
{
  Info1 tmp(other);
  swap(tmp);
  return *this;
}

void Info1::swap(Info1 & other)
{
  std::swap(sstring_, other.sstring_);

}

Info1::~Info1()
{
  delete(sstring_);

}

void Info1::accept(Visitor *v)
{
  v->visitInfo1(this);
}

Info1 *Info1::clone() const
{
  return new Info1(*this);
}



/********************   Info_    ********************/
Info_::Info_()
{

}

Info_::Info_(const Info_ & other)
{

}

Info_ &Info_::operator=(const Info_ & other)
{
  Info_ tmp(other);
  swap(tmp);
  return *this;
}

void Info_::swap(Info_ & other)
{

}

Info_::~Info_()
{

}

void Info_::accept(Visitor *v)
{
  v->visitInfo_(this);
}

Info_ *Info_::clone() const
{
  return new Info_(*this);
}



/********************   Exp1    ********************/
Exp1::Exp1(Intsize *p1, Int *p2)
{
  intsize_ = p1;
  int_ = p2;

}

Exp1::Exp1(const Exp1 & other)
{
  intsize_ = other.intsize_->clone();
  int_ = other.int_->clone();

}

Exp1 &Exp1::operator=(const Exp1 & other)
{
  Exp1 tmp(other);
  swap(tmp);
  return *this;
}

void Exp1::swap(Exp1 & other)
{
  std::swap(intsize_, other.intsize_);
  std::swap(int_, other.int_);

}

Exp1::~Exp1()
{
  delete(intsize_);
  delete(int_);

}

void Exp1::accept(Visitor *v)
{
  v->visitExp1(this);
}

Exp1 *Exp1::clone() const
{
  return new Exp1(*this);
}



/********************   Exp2    ********************/
Exp2::Exp2(Intsize *p1, SString *p2)
{
  intsize_ = p1;
  sstring_ = p2;

}

Exp2::Exp2(const Exp2 & other)
{
  intsize_ = other.intsize_->clone();
  sstring_ = other.sstring_->clone();

}

Exp2 &Exp2::operator=(const Exp2 & other)
{
  Exp2 tmp(other);
  swap(tmp);
  return *this;
}

void Exp2::swap(Exp2 & other)
{
  std::swap(intsize_, other.intsize_);
  std::swap(sstring_, other.sstring_);

}

Exp2::~Exp2()
{
  delete(intsize_);
  delete(sstring_);

}

void Exp2::accept(Visitor *v)
{
  v->visitExp2(this);
}

Exp2 *Exp2::clone() const
{
  return new Exp2(*this);
}



/********************   Exp3    ********************/
Exp3::Exp3(Intsize *p1, Int *p2)
{
  intsize_ = p1;
  int_ = p2;

}

Exp3::Exp3(const Exp3 & other)
{
  intsize_ = other.intsize_->clone();
  int_ = other.int_->clone();

}

Exp3 &Exp3::operator=(const Exp3 & other)
{
  Exp3 tmp(other);
  swap(tmp);
  return *this;
}

void Exp3::swap(Exp3 & other)
{
  std::swap(intsize_, other.intsize_);
  std::swap(int_, other.int_);

}

Exp3::~Exp3()
{
  delete(intsize_);
  delete(int_);

}

void Exp3::accept(Visitor *v)
{
  v->visitExp3(this);
}

Exp3 *Exp3::clone() const
{
  return new Exp3(*this);
}



/********************   Exp4    ********************/
Exp4::Exp4(Intsize *p1, SString *p2)
{
  intsize_ = p1;
  sstring_ = p2;

}

Exp4::Exp4(const Exp4 & other)
{
  intsize_ = other.intsize_->clone();
  sstring_ = other.sstring_->clone();

}

Exp4 &Exp4::operator=(const Exp4 & other)
{
  Exp4 tmp(other);
  swap(tmp);
  return *this;
}

void Exp4::swap(Exp4 & other)
{
  std::swap(intsize_, other.intsize_);
  std::swap(sstring_, other.sstring_);

}

Exp4::~Exp4()
{
  delete(intsize_);
  delete(sstring_);

}

void Exp4::accept(Visitor *v)
{
  v->visitExp4(this);
}

Exp4 *Exp4::clone() const
{
  return new Exp4(*this);
}



/********************   ExpId    ********************/
ExpId::ExpId(Id *p1)
{
  id_ = p1;

}

ExpId::ExpId(const ExpId & other)
{
  id_ = other.id_->clone();

}

ExpId &ExpId::operator=(const ExpId & other)
{
  ExpId tmp(other);
  swap(tmp);
  return *this;
}

void ExpId::swap(ExpId & other)
{
  std::swap(id_, other.id_);

}

ExpId::~ExpId()
{
  delete(id_);

}

void ExpId::accept(Visitor *v)
{
  v->visitExpId(this);
}

ExpId *ExpId::clone() const
{
  return new ExpId(*this);
}



/********************   Exp5    ********************/
Exp5::Exp5(Exp *p1, Id *p2)
{
  exp_ = p1;
  id_ = p2;

}

Exp5::Exp5(const Exp5 & other)
{
  exp_ = other.exp_->clone();
  id_ = other.id_->clone();

}

Exp5 &Exp5::operator=(const Exp5 & other)
{
  Exp5 tmp(other);
  swap(tmp);
  return *this;
}

void Exp5::swap(Exp5 & other)
{
  std::swap(exp_, other.exp_);
  std::swap(id_, other.id_);

}

Exp5::~Exp5()
{
  delete(exp_);
  delete(id_);

}

void Exp5::accept(Visitor *v)
{
  v->visitExp5(this);
}

Exp5 *Exp5::clone() const
{
  return new Exp5(*this);
}



/********************   Exp6    ********************/
Exp6::Exp6(Exp *p1, Int *p2)
{
  exp_ = p1;
  int_ = p2;

}

Exp6::Exp6(const Exp6 & other)
{
  exp_ = other.exp_->clone();
  int_ = other.int_->clone();

}

Exp6 &Exp6::operator=(const Exp6 & other)
{
  Exp6 tmp(other);
  swap(tmp);
  return *this;
}

void Exp6::swap(Exp6 & other)
{
  std::swap(exp_, other.exp_);
  std::swap(int_, other.int_);

}

Exp6::~Exp6()
{
  delete(exp_);
  delete(int_);

}

void Exp6::accept(Visitor *v)
{
  v->visitExp6(this);
}

Exp6 *Exp6::clone() const
{
  return new Exp6(*this);
}



/********************   Exp7    ********************/
Exp7::Exp7(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

Exp7::Exp7(const Exp7 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

Exp7 &Exp7::operator=(const Exp7 & other)
{
  Exp7 tmp(other);
  swap(tmp);
  return *this;
}

void Exp7::swap(Exp7 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

Exp7::~Exp7()
{
  delete(exp_1);
  delete(exp_2);

}

void Exp7::accept(Visitor *v)
{
  v->visitExp7(this);
}

Exp7 *Exp7::clone() const
{
  return new Exp7(*this);
}



/********************   Exp8    ********************/
Exp8::Exp8(Exp *p1, Exp *p2, Exp *p3)
{
  exp_1 = p1;
  exp_2 = p2;
  exp_3 = p3;

}

Exp8::Exp8(const Exp8 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();
  exp_3 = other.exp_3->clone();

}

Exp8 &Exp8::operator=(const Exp8 & other)
{
  Exp8 tmp(other);
  swap(tmp);
  return *this;
}

void Exp8::swap(Exp8 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);
  std::swap(exp_3, other.exp_3);

}

Exp8::~Exp8()
{
  delete(exp_1);
  delete(exp_2);
  delete(exp_3);

}

void Exp8::accept(Visitor *v)
{
  v->visitExp8(this);
}

Exp8 *Exp8::clone() const
{
  return new Exp8(*this);
}



/********************   Exp9    ********************/
Exp9::Exp9(Exp *p1, Exp *p2)
{
  exp_1 = p1;
  exp_2 = p2;

}

Exp9::Exp9(const Exp9 & other)
{
  exp_1 = other.exp_1->clone();
  exp_2 = other.exp_2->clone();

}

Exp9 &Exp9::operator=(const Exp9 & other)
{
  Exp9 tmp(other);
  swap(tmp);
  return *this;
}

void Exp9::swap(Exp9 & other)
{
  std::swap(exp_1, other.exp_1);
  std::swap(exp_2, other.exp_2);

}

Exp9::~Exp9()
{
  delete(exp_1);
  delete(exp_2);

}

void Exp9::accept(Visitor *v)
{
  v->visitExp9(this);
}

Exp9 *Exp9::clone() const
{
  return new Exp9(*this);
}



/********************   Exp10    ********************/
Exp10::Exp10(Primop *p1, ListExp *p2, ListInt *p3)
{
  primop_ = p1;
  listexp_ = p2;
  listint_ = p3;

}

Exp10::Exp10(const Exp10 & other)
{
  primop_ = other.primop_->clone();
  listexp_ = other.listexp_->clone();
  listint_ = other.listint_->clone();

}

Exp10 &Exp10::operator=(const Exp10 & other)
{
  Exp10 tmp(other);
  swap(tmp);
  return *this;
}

void Exp10::swap(Exp10 & other)
{
  std::swap(primop_, other.primop_);
  std::swap(listexp_, other.listexp_);
  std::swap(listint_, other.listint_);

}

Exp10::~Exp10()
{
  delete(primop_);
  delete(listexp_);
  delete(listint_);

}

void Exp10::accept(Visitor *v)
{
  v->visitExp10(this);
}

Exp10 *Exp10::clone() const
{
  return new Exp10(*this);
}



/********************   Primop_add    ********************/
Primop_add::Primop_add()
{

}

Primop_add::Primop_add(const Primop_add & other)
{

}

Primop_add &Primop_add::operator=(const Primop_add & other)
{
  Primop_add tmp(other);
  swap(tmp);
  return *this;
}

void Primop_add::swap(Primop_add & other)
{

}

Primop_add::~Primop_add()
{

}

void Primop_add::accept(Visitor *v)
{
  v->visitPrimop_add(this);
}

Primop_add *Primop_add::clone() const
{
  return new Primop_add(*this);
}



/********************   Primop_sub    ********************/
Primop_sub::Primop_sub()
{

}

Primop_sub::Primop_sub(const Primop_sub & other)
{

}

Primop_sub &Primop_sub::operator=(const Primop_sub & other)
{
  Primop_sub tmp(other);
  swap(tmp);
  return *this;
}

void Primop_sub::swap(Primop_sub & other)
{

}

Primop_sub::~Primop_sub()
{

}

void Primop_sub::accept(Visitor *v)
{
  v->visitPrimop_sub(this);
}

Primop_sub *Primop_sub::clone() const
{
  return new Primop_sub(*this);
}



/********************   Primop_mul    ********************/
Primop_mul::Primop_mul()
{

}

Primop_mul::Primop_mul(const Primop_mul & other)
{

}

Primop_mul &Primop_mul::operator=(const Primop_mul & other)
{
  Primop_mul tmp(other);
  swap(tmp);
  return *this;
}

void Primop_mul::swap(Primop_mul & other)
{

}

Primop_mul::~Primop_mul()
{

}

void Primop_mul::accept(Visitor *v)
{
  v->visitPrimop_mul(this);
}

Primop_mul *Primop_mul::clone() const
{
  return new Primop_mul(*this);
}



/********************   Primop_div    ********************/
Primop_div::Primop_div()
{

}

Primop_div::Primop_div(const Primop_div & other)
{

}

Primop_div &Primop_div::operator=(const Primop_div & other)
{
  Primop_div tmp(other);
  swap(tmp);
  return *this;
}

void Primop_div::swap(Primop_div & other)
{

}

Primop_div::~Primop_div()
{

}

void Primop_div::accept(Visitor *v)
{
  v->visitPrimop_div(this);
}

Primop_div *Primop_div::clone() const
{
  return new Primop_div(*this);
}



/********************   Primop_mod    ********************/
Primop_mod::Primop_mod()
{

}

Primop_mod::Primop_mod(const Primop_mod & other)
{

}

Primop_mod &Primop_mod::operator=(const Primop_mod & other)
{
  Primop_mod tmp(other);
  swap(tmp);
  return *this;
}

void Primop_mod::swap(Primop_mod & other)
{

}

Primop_mod::~Primop_mod()
{

}

void Primop_mod::accept(Visitor *v)
{
  v->visitPrimop_mod(this);
}

Primop_mod *Primop_mod::clone() const
{
  return new Primop_mod(*this);
}



/********************   Primop_lt    ********************/
Primop_lt::Primop_lt()
{

}

Primop_lt::Primop_lt(const Primop_lt & other)
{

}

Primop_lt &Primop_lt::operator=(const Primop_lt & other)
{
  Primop_lt tmp(other);
  swap(tmp);
  return *this;
}

void Primop_lt::swap(Primop_lt & other)
{

}

Primop_lt::~Primop_lt()
{

}

void Primop_lt::accept(Visitor *v)
{
  v->visitPrimop_lt(this);
}

Primop_lt *Primop_lt::clone() const
{
  return new Primop_lt(*this);
}



/********************   Primop_leq    ********************/
Primop_leq::Primop_leq()
{

}

Primop_leq::Primop_leq(const Primop_leq & other)
{

}

Primop_leq &Primop_leq::operator=(const Primop_leq & other)
{
  Primop_leq tmp(other);
  swap(tmp);
  return *this;
}

void Primop_leq::swap(Primop_leq & other)
{

}

Primop_leq::~Primop_leq()
{

}

void Primop_leq::accept(Visitor *v)
{
  v->visitPrimop_leq(this);
}

Primop_leq *Primop_leq::clone() const
{
  return new Primop_leq(*this);
}



/********************   Primop_gt    ********************/
Primop_gt::Primop_gt()
{

}

Primop_gt::Primop_gt(const Primop_gt & other)
{

}

Primop_gt &Primop_gt::operator=(const Primop_gt & other)
{
  Primop_gt tmp(other);
  swap(tmp);
  return *this;
}

void Primop_gt::swap(Primop_gt & other)
{

}

Primop_gt::~Primop_gt()
{

}

void Primop_gt::accept(Visitor *v)
{
  v->visitPrimop_gt(this);
}

Primop_gt *Primop_gt::clone() const
{
  return new Primop_gt(*this);
}



/********************   Primop_geq    ********************/
Primop_geq::Primop_geq()
{

}

Primop_geq::Primop_geq(const Primop_geq & other)
{

}

Primop_geq &Primop_geq::operator=(const Primop_geq & other)
{
  Primop_geq tmp(other);
  swap(tmp);
  return *this;
}

void Primop_geq::swap(Primop_geq & other)
{

}

Primop_geq::~Primop_geq()
{

}

void Primop_geq::accept(Visitor *v)
{
  v->visitPrimop_geq(this);
}

Primop_geq *Primop_geq::clone() const
{
  return new Primop_geq(*this);
}



/********************   Primop_eq    ********************/
Primop_eq::Primop_eq()
{

}

Primop_eq::Primop_eq(const Primop_eq & other)
{

}

Primop_eq &Primop_eq::operator=(const Primop_eq & other)
{
  Primop_eq tmp(other);
  swap(tmp);
  return *this;
}

void Primop_eq::swap(Primop_eq & other)
{

}

Primop_eq::~Primop_eq()
{

}

void Primop_eq::accept(Visitor *v)
{
  v->visitPrimop_eq(this);
}

Primop_eq *Primop_eq::clone() const
{
  return new Primop_eq(*this);
}



/********************   Primop_neq    ********************/
Primop_neq::Primop_neq()
{

}

Primop_neq::Primop_neq(const Primop_neq & other)
{

}

Primop_neq &Primop_neq::operator=(const Primop_neq & other)
{
  Primop_neq tmp(other);
  swap(tmp);
  return *this;
}

void Primop_neq::swap(Primop_neq & other)
{

}

Primop_neq::~Primop_neq()
{

}

void Primop_neq::accept(Visitor *v)
{
  v->visitPrimop_neq(this);
}

Primop_neq *Primop_neq::clone() const
{
  return new Primop_neq(*this);
}



/********************   Primop_pad    ********************/
Primop_pad::Primop_pad()
{

}

Primop_pad::Primop_pad(const Primop_pad & other)
{

}

Primop_pad &Primop_pad::operator=(const Primop_pad & other)
{
  Primop_pad tmp(other);
  swap(tmp);
  return *this;
}

void Primop_pad::swap(Primop_pad & other)
{

}

Primop_pad::~Primop_pad()
{

}

void Primop_pad::accept(Visitor *v)
{
  v->visitPrimop_pad(this);
}

Primop_pad *Primop_pad::clone() const
{
  return new Primop_pad(*this);
}



/********************   Primop_asUInt    ********************/
Primop_asUInt::Primop_asUInt()
{

}

Primop_asUInt::Primop_asUInt(const Primop_asUInt & other)
{

}

Primop_asUInt &Primop_asUInt::operator=(const Primop_asUInt & other)
{
  Primop_asUInt tmp(other);
  swap(tmp);
  return *this;
}

void Primop_asUInt::swap(Primop_asUInt & other)
{

}

Primop_asUInt::~Primop_asUInt()
{

}

void Primop_asUInt::accept(Visitor *v)
{
  v->visitPrimop_asUInt(this);
}

Primop_asUInt *Primop_asUInt::clone() const
{
  return new Primop_asUInt(*this);
}



/********************   Primop_asSInt    ********************/
Primop_asSInt::Primop_asSInt()
{

}

Primop_asSInt::Primop_asSInt(const Primop_asSInt & other)
{

}

Primop_asSInt &Primop_asSInt::operator=(const Primop_asSInt & other)
{
  Primop_asSInt tmp(other);
  swap(tmp);
  return *this;
}

void Primop_asSInt::swap(Primop_asSInt & other)
{

}

Primop_asSInt::~Primop_asSInt()
{

}

void Primop_asSInt::accept(Visitor *v)
{
  v->visitPrimop_asSInt(this);
}

Primop_asSInt *Primop_asSInt::clone() const
{
  return new Primop_asSInt(*this);
}



/********************   Primop_asClock    ********************/
Primop_asClock::Primop_asClock()
{

}

Primop_asClock::Primop_asClock(const Primop_asClock & other)
{

}

Primop_asClock &Primop_asClock::operator=(const Primop_asClock & other)
{
  Primop_asClock tmp(other);
  swap(tmp);
  return *this;
}

void Primop_asClock::swap(Primop_asClock & other)
{

}

Primop_asClock::~Primop_asClock()
{

}

void Primop_asClock::accept(Visitor *v)
{
  v->visitPrimop_asClock(this);
}

Primop_asClock *Primop_asClock::clone() const
{
  return new Primop_asClock(*this);
}



/********************   Primop_shl    ********************/
Primop_shl::Primop_shl()
{

}

Primop_shl::Primop_shl(const Primop_shl & other)
{

}

Primop_shl &Primop_shl::operator=(const Primop_shl & other)
{
  Primop_shl tmp(other);
  swap(tmp);
  return *this;
}

void Primop_shl::swap(Primop_shl & other)
{

}

Primop_shl::~Primop_shl()
{

}

void Primop_shl::accept(Visitor *v)
{
  v->visitPrimop_shl(this);
}

Primop_shl *Primop_shl::clone() const
{
  return new Primop_shl(*this);
}



/********************   Primop_shr    ********************/
Primop_shr::Primop_shr()
{

}

Primop_shr::Primop_shr(const Primop_shr & other)
{

}

Primop_shr &Primop_shr::operator=(const Primop_shr & other)
{
  Primop_shr tmp(other);
  swap(tmp);
  return *this;
}

void Primop_shr::swap(Primop_shr & other)
{

}

Primop_shr::~Primop_shr()
{

}

void Primop_shr::accept(Visitor *v)
{
  v->visitPrimop_shr(this);
}

Primop_shr *Primop_shr::clone() const
{
  return new Primop_shr(*this);
}



/********************   Primop_dshl    ********************/
Primop_dshl::Primop_dshl()
{

}

Primop_dshl::Primop_dshl(const Primop_dshl & other)
{

}

Primop_dshl &Primop_dshl::operator=(const Primop_dshl & other)
{
  Primop_dshl tmp(other);
  swap(tmp);
  return *this;
}

void Primop_dshl::swap(Primop_dshl & other)
{

}

Primop_dshl::~Primop_dshl()
{

}

void Primop_dshl::accept(Visitor *v)
{
  v->visitPrimop_dshl(this);
}

Primop_dshl *Primop_dshl::clone() const
{
  return new Primop_dshl(*this);
}



/********************   Primop_dshr    ********************/
Primop_dshr::Primop_dshr()
{

}

Primop_dshr::Primop_dshr(const Primop_dshr & other)
{

}

Primop_dshr &Primop_dshr::operator=(const Primop_dshr & other)
{
  Primop_dshr tmp(other);
  swap(tmp);
  return *this;
}

void Primop_dshr::swap(Primop_dshr & other)
{

}

Primop_dshr::~Primop_dshr()
{

}

void Primop_dshr::accept(Visitor *v)
{
  v->visitPrimop_dshr(this);
}

Primop_dshr *Primop_dshr::clone() const
{
  return new Primop_dshr(*this);
}



/********************   Primop_cvt    ********************/
Primop_cvt::Primop_cvt()
{

}

Primop_cvt::Primop_cvt(const Primop_cvt & other)
{

}

Primop_cvt &Primop_cvt::operator=(const Primop_cvt & other)
{
  Primop_cvt tmp(other);
  swap(tmp);
  return *this;
}

void Primop_cvt::swap(Primop_cvt & other)
{

}

Primop_cvt::~Primop_cvt()
{

}

void Primop_cvt::accept(Visitor *v)
{
  v->visitPrimop_cvt(this);
}

Primop_cvt *Primop_cvt::clone() const
{
  return new Primop_cvt(*this);
}



/********************   Primop_neg    ********************/
Primop_neg::Primop_neg()
{

}

Primop_neg::Primop_neg(const Primop_neg & other)
{

}

Primop_neg &Primop_neg::operator=(const Primop_neg & other)
{
  Primop_neg tmp(other);
  swap(tmp);
  return *this;
}

void Primop_neg::swap(Primop_neg & other)
{

}

Primop_neg::~Primop_neg()
{

}

void Primop_neg::accept(Visitor *v)
{
  v->visitPrimop_neg(this);
}

Primop_neg *Primop_neg::clone() const
{
  return new Primop_neg(*this);
}



/********************   Primop_not    ********************/
Primop_not::Primop_not()
{

}

Primop_not::Primop_not(const Primop_not & other)
{

}

Primop_not &Primop_not::operator=(const Primop_not & other)
{
  Primop_not tmp(other);
  swap(tmp);
  return *this;
}

void Primop_not::swap(Primop_not & other)
{

}

Primop_not::~Primop_not()
{

}

void Primop_not::accept(Visitor *v)
{
  v->visitPrimop_not(this);
}

Primop_not *Primop_not::clone() const
{
  return new Primop_not(*this);
}



/********************   Primop_and    ********************/
Primop_and::Primop_and()
{

}

Primop_and::Primop_and(const Primop_and & other)
{

}

Primop_and &Primop_and::operator=(const Primop_and & other)
{
  Primop_and tmp(other);
  swap(tmp);
  return *this;
}

void Primop_and::swap(Primop_and & other)
{

}

Primop_and::~Primop_and()
{

}

void Primop_and::accept(Visitor *v)
{
  v->visitPrimop_and(this);
}

Primop_and *Primop_and::clone() const
{
  return new Primop_and(*this);
}



/********************   Primop_or    ********************/
Primop_or::Primop_or()
{

}

Primop_or::Primop_or(const Primop_or & other)
{

}

Primop_or &Primop_or::operator=(const Primop_or & other)
{
  Primop_or tmp(other);
  swap(tmp);
  return *this;
}

void Primop_or::swap(Primop_or & other)
{

}

Primop_or::~Primop_or()
{

}

void Primop_or::accept(Visitor *v)
{
  v->visitPrimop_or(this);
}

Primop_or *Primop_or::clone() const
{
  return new Primop_or(*this);
}



/********************   Primop_xor    ********************/
Primop_xor::Primop_xor()
{

}

Primop_xor::Primop_xor(const Primop_xor & other)
{

}

Primop_xor &Primop_xor::operator=(const Primop_xor & other)
{
  Primop_xor tmp(other);
  swap(tmp);
  return *this;
}

void Primop_xor::swap(Primop_xor & other)
{

}

Primop_xor::~Primop_xor()
{

}

void Primop_xor::accept(Visitor *v)
{
  v->visitPrimop_xor(this);
}

Primop_xor *Primop_xor::clone() const
{
  return new Primop_xor(*this);
}



/********************   Primop_andr    ********************/
Primop_andr::Primop_andr()
{

}

Primop_andr::Primop_andr(const Primop_andr & other)
{

}

Primop_andr &Primop_andr::operator=(const Primop_andr & other)
{
  Primop_andr tmp(other);
  swap(tmp);
  return *this;
}

void Primop_andr::swap(Primop_andr & other)
{

}

Primop_andr::~Primop_andr()
{

}

void Primop_andr::accept(Visitor *v)
{
  v->visitPrimop_andr(this);
}

Primop_andr *Primop_andr::clone() const
{
  return new Primop_andr(*this);
}



/********************   Primop_orr    ********************/
Primop_orr::Primop_orr()
{

}

Primop_orr::Primop_orr(const Primop_orr & other)
{

}

Primop_orr &Primop_orr::operator=(const Primop_orr & other)
{
  Primop_orr tmp(other);
  swap(tmp);
  return *this;
}

void Primop_orr::swap(Primop_orr & other)
{

}

Primop_orr::~Primop_orr()
{

}

void Primop_orr::accept(Visitor *v)
{
  v->visitPrimop_orr(this);
}

Primop_orr *Primop_orr::clone() const
{
  return new Primop_orr(*this);
}



/********************   Primop_xorr    ********************/
Primop_xorr::Primop_xorr()
{

}

Primop_xorr::Primop_xorr(const Primop_xorr & other)
{

}

Primop_xorr &Primop_xorr::operator=(const Primop_xorr & other)
{
  Primop_xorr tmp(other);
  swap(tmp);
  return *this;
}

void Primop_xorr::swap(Primop_xorr & other)
{

}

Primop_xorr::~Primop_xorr()
{

}

void Primop_xorr::accept(Visitor *v)
{
  v->visitPrimop_xorr(this);
}

Primop_xorr *Primop_xorr::clone() const
{
  return new Primop_xorr(*this);
}



/********************   Primop_cat    ********************/
Primop_cat::Primop_cat()
{

}

Primop_cat::Primop_cat(const Primop_cat & other)
{

}

Primop_cat &Primop_cat::operator=(const Primop_cat & other)
{
  Primop_cat tmp(other);
  swap(tmp);
  return *this;
}

void Primop_cat::swap(Primop_cat & other)
{

}

Primop_cat::~Primop_cat()
{

}

void Primop_cat::accept(Visitor *v)
{
  v->visitPrimop_cat(this);
}

Primop_cat *Primop_cat::clone() const
{
  return new Primop_cat(*this);
}



/********************   Primop_bits    ********************/
Primop_bits::Primop_bits()
{

}

Primop_bits::Primop_bits(const Primop_bits & other)
{

}

Primop_bits &Primop_bits::operator=(const Primop_bits & other)
{
  Primop_bits tmp(other);
  swap(tmp);
  return *this;
}

void Primop_bits::swap(Primop_bits & other)
{

}

Primop_bits::~Primop_bits()
{

}

void Primop_bits::accept(Visitor *v)
{
  v->visitPrimop_bits(this);
}

Primop_bits *Primop_bits::clone() const
{
  return new Primop_bits(*this);
}



/********************   Primop_head    ********************/
Primop_head::Primop_head()
{

}

Primop_head::Primop_head(const Primop_head & other)
{

}

Primop_head &Primop_head::operator=(const Primop_head & other)
{
  Primop_head tmp(other);
  swap(tmp);
  return *this;
}

void Primop_head::swap(Primop_head & other)
{

}

Primop_head::~Primop_head()
{

}

void Primop_head::accept(Visitor *v)
{
  v->visitPrimop_head(this);
}

Primop_head *Primop_head::clone() const
{
  return new Primop_head(*this);
}



/********************   Primop_tail    ********************/
Primop_tail::Primop_tail()
{

}

Primop_tail::Primop_tail(const Primop_tail & other)
{

}

Primop_tail &Primop_tail::operator=(const Primop_tail & other)
{
  Primop_tail tmp(other);
  swap(tmp);
  return *this;
}

void Primop_tail::swap(Primop_tail & other)
{

}

Primop_tail::~Primop_tail()
{

}

void Primop_tail::accept(Visitor *v)
{
  v->visitPrimop_tail(this);
}

Primop_tail *Primop_tail::clone() const
{
  return new Primop_tail(*this);
}



/********************   Eid    ********************/
Eid::Eid(Ident p1)
{
  ident_ = p1;

}

Eid::Eid(const Eid & other)
{
  ident_ = other.ident_;

}

Eid &Eid::operator=(const Eid & other)
{
  Eid tmp(other);
  swap(tmp);
  return *this;
}

void Eid::swap(Eid & other)
{
  std::swap(ident_, other.ident_);

}

Eid::~Eid()
{

}

void Eid::accept(Visitor *v)
{
  v->visitEid(this);
}

Eid *Eid::clone() const
{
  return new Eid(*this);
}



/********************   Estring    ********************/
Estring::Estring(String p1)
{
  string_ = p1;

}

Estring::Estring(const Estring & other)
{
  string_ = other.string_;

}

Estring &Estring::operator=(const Estring & other)
{
  Estring tmp(other);
  swap(tmp);
  return *this;
}

void Estring::swap(Estring & other)
{
  std::swap(string_, other.string_);

}

Estring::~Estring()
{

}

void Estring::accept(Visitor *v)
{
  v->visitEstring(this);
}

Estring *Estring::clone() const
{
  return new Estring(*this);
}



/********************   Intsize1    ********************/
Intsize1::Intsize1(Int *p1)
{
  int_ = p1;

}

Intsize1::Intsize1(const Intsize1 & other)
{
  int_ = other.int_->clone();

}

Intsize1 &Intsize1::operator=(const Intsize1 & other)
{
  Intsize1 tmp(other);
  swap(tmp);
  return *this;
}

void Intsize1::swap(Intsize1 & other)
{
  std::swap(int_, other.int_);

}

Intsize1::~Intsize1()
{
  delete(int_);

}

void Intsize1::accept(Visitor *v)
{
  v->visitIntsize1(this);
}

Intsize1 *Intsize1::clone() const
{
  return new Intsize1(*this);
}



/********************   Intsize_    ********************/
Intsize_::Intsize_()
{

}

Intsize_::Intsize_(const Intsize_ & other)
{

}

Intsize_ &Intsize_::operator=(const Intsize_ & other)
{
  Intsize_ tmp(other);
  swap(tmp);
  return *this;
}

void Intsize_::swap(Intsize_ & other)
{

}

Intsize_::~Intsize_()
{

}

void Intsize_::accept(Visitor *v)
{
  v->visitIntsize_(this);
}

Intsize_ *Intsize_::clone() const
{
  return new Intsize_(*this);
}



/********************   Intsizefixed1    ********************/
Intsizefixed1::Intsizefixed1(Int *p1)
{
  int_ = p1;

}

Intsizefixed1::Intsizefixed1(const Intsizefixed1 & other)
{
  int_ = other.int_->clone();

}

Intsizefixed1 &Intsizefixed1::operator=(const Intsizefixed1 & other)
{
  Intsizefixed1 tmp(other);
  swap(tmp);
  return *this;
}

void Intsizefixed1::swap(Intsizefixed1 & other)
{
  std::swap(int_, other.int_);

}

Intsizefixed1::~Intsizefixed1()
{
  delete(int_);

}

void Intsizefixed1::accept(Visitor *v)
{
  v->visitIntsizefixed1(this);
}

Intsizefixed1 *Intsizefixed1::clone() const
{
  return new Intsizefixed1(*this);
}



/********************   Intsizefixed_    ********************/
Intsizefixed_::Intsizefixed_()
{

}

Intsizefixed_::Intsizefixed_(const Intsizefixed_ & other)
{

}

Intsizefixed_ &Intsizefixed_::operator=(const Intsizefixed_ & other)
{
  Intsizefixed_ tmp(other);
  swap(tmp);
  return *this;
}

void Intsizefixed_::swap(Intsizefixed_ & other)
{

}

Intsizefixed_::~Intsizefixed_()
{

}

void Intsizefixed_::accept(Visitor *v)
{
  v->visitIntsizefixed_(this);
}

Intsizefixed_ *Intsizefixed_::clone() const
{
  return new Intsizefixed_(*this);
}



/********************   Eint    ********************/
Eint::Eint(Integer p1)
{
  integer_ = p1;

}

Eint::Eint(const Eint & other)
{
  integer_ = other.integer_;

}

Eint &Eint::operator=(const Eint & other)
{
  Eint tmp(other);
  swap(tmp);
  return *this;
}

void Eint::swap(Eint & other)
{
  std::swap(integer_, other.integer_);

}

Eint::~Eint()
{

}

void Eint::accept(Visitor *v)
{
  v->visitEint(this);
}

Eint *Eint::clone() const
{
  return new Eint(*this);
}




/********************   ListModule    ********************/

void ListModule::accept(Visitor *v)
{
  v->visitListModule(this);
}


ListModule *ListModule::clone() const
{
  return new ListModule(*this);
}


/********************   ListPort    ********************/

void ListPort::accept(Visitor *v)
{
  v->visitListPort(this);
}


ListPort *ListPort::clone() const
{
  return new ListPort(*this);
}


/********************   ListField    ********************/

void ListField::accept(Visitor *v)
{
  v->visitListField(this);
}


ListField *ListField::clone() const
{
  return new ListField(*this);
}


/********************   ListReader    ********************/

void ListReader::accept(Visitor *v)
{
  v->visitListReader(this);
}


ListReader *ListReader::clone() const
{
  return new ListReader(*this);
}


/********************   ListWriter    ********************/

void ListWriter::accept(Visitor *v)
{
  v->visitListWriter(this);
}


ListWriter *ListWriter::clone() const
{
  return new ListWriter(*this);
}


/********************   ListReadwriter    ********************/

void ListReadwriter::accept(Visitor *v)
{
  v->visitListReadwriter(this);
}


ListReadwriter *ListReadwriter::clone() const
{
  return new ListReadwriter(*this);
}


/********************   ListStmt    ********************/

void ListStmt::accept(Visitor *v)
{
  v->visitListStmt(this);
}


ListStmt *ListStmt::clone() const
{
  return new ListStmt(*this);
}


/********************   ListExp    ********************/

void ListExp::accept(Visitor *v)
{
  v->visitListExp(this);
}


ListExp *ListExp::clone() const
{
  return new ListExp(*this);
}


/********************   ListInt    ********************/

void ListInt::accept(Visitor *v)
{
  v->visitListInt(this);
}


ListInt *ListInt::clone() const
{
  return new ListInt(*this);
}



}
